#!/bin/sh

set -e

bundle exec jekyll build
#bundle exec htmlproofer ./_site --check-html --check-sri

#bundle exec rubocop -D --config .rubocop.yml
#bundle exec script/validate-html
#echo '$msg4' valhtm
gem build jekyll-theme-slate.gemspec

